version: 2.1

executors:
  node-browser:
    docker:
      - image: cimg/node:12.22-browsers
    working_directory: ~/code

commands:
  restore_repo:
    steps:
      - restore_cache:
          key: shared-goodcity-repo-{{ .Environment.CIRCLE_SHA1 }}
  restore_yarn_cache:
    steps:
      - restore_cache:
          keys:
            - shared-goodcity-yarn-packages-{{ checksum "yarn.lock" }}
  save_yarn_cache:
    steps:
      - save_cache:
          key: shared-goodcity-yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
            - ~/.cache/yarn
  yarn_install:
    steps:
      - run:
          command: yarn install --non-interactive --cache-folder ~/.cache/yarn --frozen-lockfile
  restore_bower_cache:
    steps:
      - restore_cache:
          key: shared-goodcity-bower-components-{{ checksum "bower.json" }}
  save_bower_cache:
    steps:
      - save_cache:
          key: shared-goodcity-bower-components-{{ checksum "bower.json" }}
          paths:
            - bower_components

jobs:
  checkout_code:
    executor: node-browser
    steps:
      - checkout
      - save_cache:
          key: shared-goodcity-repo-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/code

  package_dependencies:
    executor: node-browser
    steps:
      - restore_repo
      - restore_yarn_cache
      - run: yarn link
      - run: yarn add bower
      - yarn_install
      - save_yarn_cache
      - restore_bower_cache
      - run: yarn run bower install
      - save_bower_cache

  tests:
    executor: node-browser
    steps:
      - restore_repo
      - restore_yarn_cache
      - yarn_install
      - restore_bower_cache
      - run:
          name: Start Ember test server
          command: yarn run ember server --port 4203
          background: true
      - run:
          name: Wait for Ember test server to start
          command: dockerize -wait tcp://localhost:4203 -timeout 1m
      - run:
          name: Run Ember tests
          command: yarn run ember test

workflows:
  build-test-and-deploy:
    jobs:
      - checkout_code
      - package_dependencies:
          requires:
            - checkout_code
      - tests:
          requires:
            - package_dependencies
